version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tap
    versions:
    - 14.11.0
    - 15.0.0
    - 15.0.1
    - 15.0.2
    - 15.0.3
    - 15.0.4
  - dependency-name: underscore
    versions:
    - 1.12.0
    - 1.12.1
    - 1.13.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
